### ISSUE TITLE
Cannot make it work with this specific date

### ISSUE THREAD

**Issue by andrearesti** [giuseppebruno/italian-holidays#1]
Hi Bruno, sorry to bother you.
When I invoke your module with 
is_holiday = holidays.is_holiday("2013-01-24")
or
is_holiday = holidays.is_holiday(dt.datetime(2013, 1, 24))
I keep getting a nasty error like the following:

  File ~\anaconda3\lib\site-packages\italian_holidays\italian_holidays.py:23 in is_holiday
    if date_obj.month == self._easter(date_obj).month and date_obj.day == self._easter(date_obj).day:

  File ~\anaconda3\lib\site-packages\italian_holidays\italian_holidays.py:107 in _easter
    gold_number = gold_numbers[modulo]

Other dates seem to work nicely.
Would you mind looking into that?
If I am getting something wrong, please accept my apologies.
Thank you for your tme and your great work
Andrea

**Comment by giuseppebruno** [comment]
Hi Andrea,

thanks for reporting. It should be fixed now.

**Comment by andrearesti** [comment]
Hi, Giuseppe,
thanks a lot, that was very much appreciated!

**Comment by giuseppebruno** [comment]
Thanks to you, don't forget to star the repo!
Have a nice coding day :)
